### ISSUE TITLE
Deploy calaylin/bda

### ISSUE THREAD

**Issue by marius-benthin** [EdgeDauDrex/CodeStylometry-missing-joern-tools-files#1]
Hi EdgeDauDrex,
my attention has been drawn to your repository while I am trying to deploy the calaylin/bda repository on my system.
It seems like the code was not maintained for three years and I am not able to get the correct version of Bjoern that has been used in the code stylometry framework.
Are you able to reconstruct the environment of this system?
I would be very grateful if you can give me some hints about the version of Bjoern and Radare2.
Best Regards!

Related issue: https://github.com/calaylin/bda/issues/2#issue-315053262

**Comment by EdgeDauDrex** [comment]
I am working on the deployment of that system (admittedly at somewhat low priority).  If you look at my fork of the StylometrySetup repository (https://github.com/EdgeDauDrex/StylometrySetup), I have a skeleton script for the setup (binaryStylometySetup.sh), but I haven't tested and worked out the kinks yet (including such things as versioning of radare2 and bjoern, as you are especially concerned about).  It may work as is, but I cannot offer any guarantee yet.  However, it will be updated as a I work through set up and once I have a working setup I will make a note of it in the README and close this issue.
